# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/daibane/src/tycho2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/daibane/src/tycho2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/daibane/src/tycho2/CMakeFiles /home/daibane/src/tycho2/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/daibane/src/tycho2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sweep.x

# Build rule for target.
sweep.x: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sweep.x
.PHONY : sweep.x

# fast build rule for target.
sweep.x/fast:
	$(MAKE) -f CMakeFiles/sweep.x.dir/build.make CMakeFiles/sweep.x.dir/build
.PHONY : sweep.x/fast

src/Assert.o: src/Assert.cc.o

.PHONY : src/Assert.o

# target to build an object file
src/Assert.cc.o:
	$(MAKE) -f CMakeFiles/sweep.x.dir/build.make CMakeFiles/sweep.x.dir/src/Assert.cc.o
.PHONY : src/Assert.cc.o

src/Assert.i: src/Assert.cc.i

.PHONY : src/Assert.i

# target to preprocess a source file
src/Assert.cc.i:
	$(MAKE) -f CMakeFiles/sweep.x.dir/build.make CMakeFiles/sweep.x.dir/src/Assert.cc.i
.PHONY : src/Assert.cc.i

src/Assert.s: src/Assert.cc.s

.PHONY : src/Assert.s

# target to generate assembly for a file
src/Assert.cc.s:
	$(MAKE) -f CMakeFiles/sweep.x.dir/build.make CMakeFiles/sweep.x.dir/src/Assert.cc.s
.PHONY : src/Assert.cc.s

src/Comm.o: src/Comm.cc.o

.PHONY : src/Comm.o

# target to build an object file
src/Comm.cc.o:
	$(MAKE) -f CMakeFiles/sweep.x.dir/build.make CMakeFiles/sweep.x.dir/src/Comm.cc.o
.PHONY : src/Comm.cc.o

src/Comm.i: src/Comm.cc.i

.PHONY : src/Comm.i

# target to preprocess a source file
src/Comm.cc.i:
	$(MAKE) -f CMakeFiles/sweep.x.dir/build.make CMakeFiles/sweep.x.dir/src/Comm.cc.i
.PHONY : src/Comm.cc.i

src/Comm.s: src/Comm.cc.s

.PHONY : src/Comm.s

# target to generate assembly for a file
src/Comm.cc.s:
	$(MAKE) -f CMakeFiles/sweep.x.dir/build.make CMakeFiles/sweep.x.dir/src/Comm.cc.s
.PHONY : src/Comm.cc.s

src/CommSides.o: src/CommSides.cc.o

.PHONY : src/CommSides.o

# target to build an object file
src/CommSides.cc.o:
	$(MAKE) -f CMakeFiles/sweep.x.dir/build.make CMakeFiles/sweep.x.dir/src/CommSides.cc.o
.PHONY : src/CommSides.cc.o

src/CommSides.i: src/CommSides.cc.i

.PHONY : src/CommSides.i

# target to preprocess a source file
src/CommSides.cc.i:
	$(MAKE) -f CMakeFiles/sweep.x.dir/build.make CMakeFiles/sweep.x.dir/src/CommSides.cc.i
.PHONY : src/CommSides.cc.i

src/CommSides.s: src/CommSides.cc.s

.PHONY : src/CommSides.s

# target to generate assembly for a file
src/CommSides.cc.s:
	$(MAKE) -f CMakeFiles/sweep.x.dir/build.make CMakeFiles/sweep.x.dir/src/CommSides.cc.s
.PHONY : src/CommSides.cc.s

src/Global.o: src/Global.cc.o

.PHONY : src/Global.o

# target to build an object file
src/Global.cc.o:
	$(MAKE) -f CMakeFiles/sweep.x.dir/build.make CMakeFiles/sweep.x.dir/src/Global.cc.o
.PHONY : src/Global.cc.o

src/Global.i: src/Global.cc.i

.PHONY : src/Global.i

# target to preprocess a source file
src/Global.cc.i:
	$(MAKE) -f CMakeFiles/sweep.x.dir/build.make CMakeFiles/sweep.x.dir/src/Global.cc.i
.PHONY : src/Global.cc.i

src/Global.s: src/Global.cc.s

.PHONY : src/Global.s

# target to generate assembly for a file
src/Global.cc.s:
	$(MAKE) -f CMakeFiles/sweep.x.dir/build.make CMakeFiles/sweep.x.dir/src/Global.cc.s
.PHONY : src/Global.cc.s

src/GraphTraverser.o: src/GraphTraverser.cc.o

.PHONY : src/GraphTraverser.o

# target to build an object file
src/GraphTraverser.cc.o:
	$(MAKE) -f CMakeFiles/sweep.x.dir/build.make CMakeFiles/sweep.x.dir/src/GraphTraverser.cc.o
.PHONY : src/GraphTraverser.cc.o

src/GraphTraverser.i: src/GraphTraverser.cc.i

.PHONY : src/GraphTraverser.i

# target to preprocess a source file
src/GraphTraverser.cc.i:
	$(MAKE) -f CMakeFiles/sweep.x.dir/build.make CMakeFiles/sweep.x.dir/src/GraphTraverser.cc.i
.PHONY : src/GraphTraverser.cc.i

src/GraphTraverser.s: src/GraphTraverser.cc.s

.PHONY : src/GraphTraverser.s

# target to generate assembly for a file
src/GraphTraverser.cc.s:
	$(MAKE) -f CMakeFiles/sweep.x.dir/build.make CMakeFiles/sweep.x.dir/src/GraphTraverser.cc.s
.PHONY : src/GraphTraverser.cc.s

src/KeyValueReader.o: src/KeyValueReader.cc.o

.PHONY : src/KeyValueReader.o

# target to build an object file
src/KeyValueReader.cc.o:
	$(MAKE) -f CMakeFiles/sweep.x.dir/build.make CMakeFiles/sweep.x.dir/src/KeyValueReader.cc.o
.PHONY : src/KeyValueReader.cc.o

src/KeyValueReader.i: src/KeyValueReader.cc.i

.PHONY : src/KeyValueReader.i

# target to preprocess a source file
src/KeyValueReader.cc.i:
	$(MAKE) -f CMakeFiles/sweep.x.dir/build.make CMakeFiles/sweep.x.dir/src/KeyValueReader.cc.i
.PHONY : src/KeyValueReader.cc.i

src/KeyValueReader.s: src/KeyValueReader.cc.s

.PHONY : src/KeyValueReader.s

# target to generate assembly for a file
src/KeyValueReader.cc.s:
	$(MAKE) -f CMakeFiles/sweep.x.dir/build.make CMakeFiles/sweep.x.dir/src/KeyValueReader.cc.s
.PHONY : src/KeyValueReader.cc.s

src/Main.o: src/Main.cc.o

.PHONY : src/Main.o

# target to build an object file
src/Main.cc.o:
	$(MAKE) -f CMakeFiles/sweep.x.dir/build.make CMakeFiles/sweep.x.dir/src/Main.cc.o
.PHONY : src/Main.cc.o

src/Main.i: src/Main.cc.i

.PHONY : src/Main.i

# target to preprocess a source file
src/Main.cc.i:
	$(MAKE) -f CMakeFiles/sweep.x.dir/build.make CMakeFiles/sweep.x.dir/src/Main.cc.i
.PHONY : src/Main.cc.i

src/Main.s: src/Main.cc.s

.PHONY : src/Main.s

# target to generate assembly for a file
src/Main.cc.s:
	$(MAKE) -f CMakeFiles/sweep.x.dir/build.make CMakeFiles/sweep.x.dir/src/Main.cc.s
.PHONY : src/Main.cc.s

src/ParallelMesh.o: src/ParallelMesh.cc.o

.PHONY : src/ParallelMesh.o

# target to build an object file
src/ParallelMesh.cc.o:
	$(MAKE) -f CMakeFiles/sweep.x.dir/build.make CMakeFiles/sweep.x.dir/src/ParallelMesh.cc.o
.PHONY : src/ParallelMesh.cc.o

src/ParallelMesh.i: src/ParallelMesh.cc.i

.PHONY : src/ParallelMesh.i

# target to preprocess a source file
src/ParallelMesh.cc.i:
	$(MAKE) -f CMakeFiles/sweep.x.dir/build.make CMakeFiles/sweep.x.dir/src/ParallelMesh.cc.i
.PHONY : src/ParallelMesh.cc.i

src/ParallelMesh.s: src/ParallelMesh.cc.s

.PHONY : src/ParallelMesh.s

# target to generate assembly for a file
src/ParallelMesh.cc.s:
	$(MAKE) -f CMakeFiles/sweep.x.dir/build.make CMakeFiles/sweep.x.dir/src/ParallelMesh.cc.s
.PHONY : src/ParallelMesh.cc.s

src/Problem.o: src/Problem.cc.o

.PHONY : src/Problem.o

# target to build an object file
src/Problem.cc.o:
	$(MAKE) -f CMakeFiles/sweep.x.dir/build.make CMakeFiles/sweep.x.dir/src/Problem.cc.o
.PHONY : src/Problem.cc.o

src/Problem.i: src/Problem.cc.i

.PHONY : src/Problem.i

# target to preprocess a source file
src/Problem.cc.i:
	$(MAKE) -f CMakeFiles/sweep.x.dir/build.make CMakeFiles/sweep.x.dir/src/Problem.cc.i
.PHONY : src/Problem.cc.i

src/Problem.s: src/Problem.cc.s

.PHONY : src/Problem.s

# target to generate assembly for a file
src/Problem.cc.s:
	$(MAKE) -f CMakeFiles/sweep.x.dir/build.make CMakeFiles/sweep.x.dir/src/Problem.cc.s
.PHONY : src/Problem.cc.s

src/PsiData.o: src/PsiData.cc.o

.PHONY : src/PsiData.o

# target to build an object file
src/PsiData.cc.o:
	$(MAKE) -f CMakeFiles/sweep.x.dir/build.make CMakeFiles/sweep.x.dir/src/PsiData.cc.o
.PHONY : src/PsiData.cc.o

src/PsiData.i: src/PsiData.cc.i

.PHONY : src/PsiData.i

# target to preprocess a source file
src/PsiData.cc.i:
	$(MAKE) -f CMakeFiles/sweep.x.dir/build.make CMakeFiles/sweep.x.dir/src/PsiData.cc.i
.PHONY : src/PsiData.cc.i

src/PsiData.s: src/PsiData.cc.s

.PHONY : src/PsiData.s

# target to generate assembly for a file
src/PsiData.cc.s:
	$(MAKE) -f CMakeFiles/sweep.x.dir/build.make CMakeFiles/sweep.x.dir/src/PsiData.cc.s
.PHONY : src/PsiData.cc.s

src/Quadrature.o: src/Quadrature.cc.o

.PHONY : src/Quadrature.o

# target to build an object file
src/Quadrature.cc.o:
	$(MAKE) -f CMakeFiles/sweep.x.dir/build.make CMakeFiles/sweep.x.dir/src/Quadrature.cc.o
.PHONY : src/Quadrature.cc.o

src/Quadrature.i: src/Quadrature.cc.i

.PHONY : src/Quadrature.i

# target to preprocess a source file
src/Quadrature.cc.i:
	$(MAKE) -f CMakeFiles/sweep.x.dir/build.make CMakeFiles/sweep.x.dir/src/Quadrature.cc.i
.PHONY : src/Quadrature.cc.i

src/Quadrature.s: src/Quadrature.cc.s

.PHONY : src/Quadrature.s

# target to generate assembly for a file
src/Quadrature.cc.s:
	$(MAKE) -f CMakeFiles/sweep.x.dir/build.make CMakeFiles/sweep.x.dir/src/Quadrature.cc.s
.PHONY : src/Quadrature.cc.s

src/SerialMesh.o: src/SerialMesh.cc.o

.PHONY : src/SerialMesh.o

# target to build an object file
src/SerialMesh.cc.o:
	$(MAKE) -f CMakeFiles/sweep.x.dir/build.make CMakeFiles/sweep.x.dir/src/SerialMesh.cc.o
.PHONY : src/SerialMesh.cc.o

src/SerialMesh.i: src/SerialMesh.cc.i

.PHONY : src/SerialMesh.i

# target to preprocess a source file
src/SerialMesh.cc.i:
	$(MAKE) -f CMakeFiles/sweep.x.dir/build.make CMakeFiles/sweep.x.dir/src/SerialMesh.cc.i
.PHONY : src/SerialMesh.cc.i

src/SerialMesh.s: src/SerialMesh.cc.s

.PHONY : src/SerialMesh.s

# target to generate assembly for a file
src/SerialMesh.cc.s:
	$(MAKE) -f CMakeFiles/sweep.x.dir/build.make CMakeFiles/sweep.x.dir/src/SerialMesh.cc.s
.PHONY : src/SerialMesh.cc.s

src/Sweeper.o: src/Sweeper.cc.o

.PHONY : src/Sweeper.o

# target to build an object file
src/Sweeper.cc.o:
	$(MAKE) -f CMakeFiles/sweep.x.dir/build.make CMakeFiles/sweep.x.dir/src/Sweeper.cc.o
.PHONY : src/Sweeper.cc.o

src/Sweeper.i: src/Sweeper.cc.i

.PHONY : src/Sweeper.i

# target to preprocess a source file
src/Sweeper.cc.i:
	$(MAKE) -f CMakeFiles/sweep.x.dir/build.make CMakeFiles/sweep.x.dir/src/Sweeper.cc.i
.PHONY : src/Sweeper.cc.i

src/Sweeper.s: src/Sweeper.cc.s

.PHONY : src/Sweeper.s

# target to generate assembly for a file
src/Sweeper.cc.s:
	$(MAKE) -f CMakeFiles/sweep.x.dir/build.make CMakeFiles/sweep.x.dir/src/Sweeper.cc.s
.PHONY : src/Sweeper.cc.s

src/TychoMesh.o: src/TychoMesh.cc.o

.PHONY : src/TychoMesh.o

# target to build an object file
src/TychoMesh.cc.o:
	$(MAKE) -f CMakeFiles/sweep.x.dir/build.make CMakeFiles/sweep.x.dir/src/TychoMesh.cc.o
.PHONY : src/TychoMesh.cc.o

src/TychoMesh.i: src/TychoMesh.cc.i

.PHONY : src/TychoMesh.i

# target to preprocess a source file
src/TychoMesh.cc.i:
	$(MAKE) -f CMakeFiles/sweep.x.dir/build.make CMakeFiles/sweep.x.dir/src/TychoMesh.cc.i
.PHONY : src/TychoMesh.cc.i

src/TychoMesh.s: src/TychoMesh.cc.s

.PHONY : src/TychoMesh.s

# target to generate assembly for a file
src/TychoMesh.cc.s:
	$(MAKE) -f CMakeFiles/sweep.x.dir/build.make CMakeFiles/sweep.x.dir/src/TychoMesh.cc.s
.PHONY : src/TychoMesh.cc.s

src/TychoMeshIO.o: src/TychoMeshIO.cc.o

.PHONY : src/TychoMeshIO.o

# target to build an object file
src/TychoMeshIO.cc.o:
	$(MAKE) -f CMakeFiles/sweep.x.dir/build.make CMakeFiles/sweep.x.dir/src/TychoMeshIO.cc.o
.PHONY : src/TychoMeshIO.cc.o

src/TychoMeshIO.i: src/TychoMeshIO.cc.i

.PHONY : src/TychoMeshIO.i

# target to preprocess a source file
src/TychoMeshIO.cc.i:
	$(MAKE) -f CMakeFiles/sweep.x.dir/build.make CMakeFiles/sweep.x.dir/src/TychoMeshIO.cc.i
.PHONY : src/TychoMeshIO.cc.i

src/TychoMeshIO.s: src/TychoMeshIO.cc.s

.PHONY : src/TychoMeshIO.s

# target to generate assembly for a file
src/TychoMeshIO.cc.s:
	$(MAKE) -f CMakeFiles/sweep.x.dir/build.make CMakeFiles/sweep.x.dir/src/TychoMeshIO.cc.s
.PHONY : src/TychoMeshIO.cc.s

src/Util.o: src/Util.cc.o

.PHONY : src/Util.o

# target to build an object file
src/Util.cc.o:
	$(MAKE) -f CMakeFiles/sweep.x.dir/build.make CMakeFiles/sweep.x.dir/src/Util.cc.o
.PHONY : src/Util.cc.o

src/Util.i: src/Util.cc.i

.PHONY : src/Util.i

# target to preprocess a source file
src/Util.cc.i:
	$(MAKE) -f CMakeFiles/sweep.x.dir/build.make CMakeFiles/sweep.x.dir/src/Util.cc.i
.PHONY : src/Util.cc.i

src/Util.s: src/Util.cc.s

.PHONY : src/Util.s

# target to generate assembly for a file
src/Util.cc.s:
	$(MAKE) -f CMakeFiles/sweep.x.dir/build.make CMakeFiles/sweep.x.dir/src/Util.cc.s
.PHONY : src/Util.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... sweep.x"
	@echo "... edit_cache"
	@echo "... src/Assert.o"
	@echo "... src/Assert.i"
	@echo "... src/Assert.s"
	@echo "... src/Comm.o"
	@echo "... src/Comm.i"
	@echo "... src/Comm.s"
	@echo "... src/CommSides.o"
	@echo "... src/CommSides.i"
	@echo "... src/CommSides.s"
	@echo "... src/Global.o"
	@echo "... src/Global.i"
	@echo "... src/Global.s"
	@echo "... src/GraphTraverser.o"
	@echo "... src/GraphTraverser.i"
	@echo "... src/GraphTraverser.s"
	@echo "... src/KeyValueReader.o"
	@echo "... src/KeyValueReader.i"
	@echo "... src/KeyValueReader.s"
	@echo "... src/Main.o"
	@echo "... src/Main.i"
	@echo "... src/Main.s"
	@echo "... src/ParallelMesh.o"
	@echo "... src/ParallelMesh.i"
	@echo "... src/ParallelMesh.s"
	@echo "... src/Problem.o"
	@echo "... src/Problem.i"
	@echo "... src/Problem.s"
	@echo "... src/PsiData.o"
	@echo "... src/PsiData.i"
	@echo "... src/PsiData.s"
	@echo "... src/Quadrature.o"
	@echo "... src/Quadrature.i"
	@echo "... src/Quadrature.s"
	@echo "... src/SerialMesh.o"
	@echo "... src/SerialMesh.i"
	@echo "... src/SerialMesh.s"
	@echo "... src/Sweeper.o"
	@echo "... src/Sweeper.i"
	@echo "... src/Sweeper.s"
	@echo "... src/TychoMesh.o"
	@echo "... src/TychoMesh.i"
	@echo "... src/TychoMesh.s"
	@echo "... src/TychoMeshIO.o"
	@echo "... src/TychoMeshIO.i"
	@echo "... src/TychoMeshIO.s"
	@echo "... src/Util.o"
	@echo "... src/Util.i"
	@echo "... src/Util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

